import { describe,expect,it,vi } from "vitest";
import { exportProgramsFromDatabase,transformPrograms,type ProgramExportInput } from "../programs";
const base=():ProgramExportInput=>({programs:[{id:"p",slug:"test-bs",title:"Test",credential:"Bachelor of Science",catalogYear:"2025",totalCredits:120,description:"d",sourcePid:"pid",syncedAt:"2026-01-01"}],groups:[{id:"g1",programId:"p",parentId:null,title:"Root",category:"core",ruleType:"all_of",minimumSelections:null,maximumSelections:null,minimumCredits:3,rawExcerpt:null,ruleMetadata:null,sortOrder:1},{id:"g2",programId:"p",parentId:"g1",title:"Choice",category:"major",ruleType:"choose_n",minimumSelections:1,maximumSelections:2,minimumCredits:null,rawExcerpt:"choose",ruleMetadata:{minimumSelections:1},sortOrder:2},{id:"g3",programId:"p",parentId:"g2",title:"Deep",category:"elective",ruleType:"free_elective",minimumSelections:null,maximumSelections:null,minimumCredits:6,rawExcerpt:null,ruleMetadata:null,sortOrder:3}],courses:[{groupId:"g1",id:"required",courseCode:"CS100",title:"Required",credits:3,optional:false,sortOrder:2},{groupId:"g1",id:"optional",courseCode:"CS199",title:"Optional",credits:3,optional:true,sortOrder:1},{groupId:"g2",id:"choice1",courseCode:"CS200",title:"Choice 1",credits:3,optional:false,sortOrder:2},{groupId:"g2",id:"choice2",courseCode:"CS201",title:"Choice 2",credits:3,optional:false,sortOrder:1}],texts:[{groupId:"g3",id:"policy",text:"Eligibility policy",unparsed:false,sortOrder:2},{groupId:"g3",id:"raw",text:"Unparsed note",unparsed:true,sortOrder:1}],edges:[{programId:"p",source:"MAT100",target:"CS100",type:"prerequisite",label:"Prerequisite",title:"Math",credits:3,resolutionStatus:"resolved"},{programId:"p",source:"CS200",target:"CS201",type:"corequisite",label:null,title:"Choice 1",credits:3,resolutionStatus:"resolved"}]});
describe("program exporter fidelity",()=>{
 it("preserves deep nesting, order, rules, text, and required counts",()=>{const output=transformPrograms(base());const p=output.bySlug["test-bs"];expect(p.groups[0].items.map(i=>i.id)).toEqual(["optional","required","g2"]);expect(p.groups[0].items[2].subItems?.at(-1)?.subItems?.map(i=>i.id)).toEqual(["raw","policy"]);expect(p.requiredCourseCount).toBe(2);expect(p.nodes.find(n=>n.code==="MAT 100")?.isExternal).toBe(true);expect(p.edges.map(e=>e.type)).toEqual(["prerequisite","corequisite"]);});
 it("is deterministic, deduplicates edges, and rejects bad structures",()=>{const input=base();input.edges.push({...input.edges[0]});expect(transformPrograms({...input,groups:[...input.groups].reverse(),courses:[...input.courses].reverse()})).toEqual(transformPrograms(input));const orphan=base();orphan.groups[1].parentId="missing";expect(()=>transformPrograms(orphan)).toThrow(/missing parent/);const cycle=base();cycle.groups[0].parentId="g3";expect(()=>transformPrograms(cycle)).toThrow(/cycle/);const duplicate=base();duplicate.programs.push({...duplicate.programs[0],id:"p2"});expect(()=>transformPrograms(duplicate)).toThrow(/duplicate program slug/);});
 it("rejects unknown relationships and broken targets",()=>{const input=base();input.edges[0].type="recommended";expect(()=>transformPrograms(input)).toThrow(/Unknown relationship/);});
 it("uses a repeatable-read, read-only transaction",async()=>{const input=base();const query=vi.fn().mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:input.programs}).mockResolvedValueOnce({rows:input.groups}).mockResolvedValueOnce({rows:input.courses}).mockResolvedValueOnce({rows:input.texts}).mockResolvedValueOnce({rows:input.edges}).mockResolvedValueOnce({rows:[]});const release=vi.fn();await exportProgramsFromDatabase({connect:vi.fn().mockResolvedValue({query,release})} as never);expect(query).toHaveBeenNthCalledWith(1,"BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");expect(query).toHaveBeenLastCalledWith("COMMIT");expect(release).toHaveBeenCalled();});
});
