import { describe,expect,it } from "vitest";
import { transformCourses } from "../courses";
import { transformPrograms,type ProgramExportInput } from "../programs";
import { transformTransfers } from "../transfers";
import { transformSearch } from "../search";
import { searchAll } from "@/lib/search/globalSearch";
const programInput:ProgramExportInput={programs:[{id:"p",slug:"alpha-bs",title:"Alpha",credential:"Bachelor of Science",catalogYear:"2025",totalCredits:120,description:"",sourcePid:null,syncedAt:null}],groups:[{id:"g",programId:"p",parentId:null,title:"Core",category:"core",ruleType:"all_of",minimumSelections:null,maximumSelections:null,minimumCredits:null,rawExcerpt:null,ruleMetadata:null,sortOrder:1}],courses:[{id:"r",groupId:"g",courseCode:"CS100",title:"Intro",credits:3,optional:false,sortOrder:1}],texts:[],edges:[]};
describe("derived search export",()=>{
 const sources=()=>({programs:transformPrograms(programInput),courses:transformCourses([{catalog_course_id:"CS210",title:"Programming",pid:"p",description:null,academic_level:null,credits:null,subject_code:null}],[],null),transfers:transformTransfers([{subjectPrefix:"CS",courseNumber:"CS210",title:"Programming",pid:"a",eligibilityTimeframe:null,groupFilter2Name:"One",academicLevel:null,coursePID:null},{subjectPrefix:"CS",courseNumber:"CS210",title:"Programming",pid:"b",eligibilityTimeframe:null,groupFilter2Name:"Two",academicLevel:null,coursePID:null}],null)});
 it("contains all domain entries, preserves all transfer options, and counts them",()=>{const {programs,courses,transfers}=sources();const index=transformSearch(programs,courses,transfers);expect(index.meta).toEqual({domain:"search",counts:{entries:4}});expect(index.programs[0].slug).toBe("alpha-bs");expect(index.courses[0].catalog_course_id).toBe("CS210");expect(index.transfers).toHaveLength(2);expect(index.transfers.map(r=>r.groupFilter2Name)).toEqual(["One","Two"]);});
 it("is independent of source ordering and rejects inconsistent source records",()=>{const {programs,courses,transfers}=sources();const expected=transformSearch(programs,courses,transfers);expect(transformSearch({...programs,directory:[...programs.directory].reverse()},{...courses,summaries:[...courses.summaries].reverse()},{...transfers,rows:[...transfers.rows].reverse()})).toEqual(expected);expect(()=>transformSearch({...programs,directory:[...programs.directory,...programs.directory]},courses,transfers)).toThrow(/counts|Invalid program/);expect(()=>transformSearch(programs,{...courses,summaries:[{catalog_course_id:"NOPE",title:"Bad"}]},transfers)).toThrow(/Invalid course/);});
 it("leaves current runtime search behavior compatible with realistic terms",async()=>{const result=await searchAll("CS210");expect(result.results.courses.some(entry=>entry.id==="CS210")).toBe(true);expect(result.results.transfers.some(entry=>entry.type==="transfer"&&entry.id==="CS210"&&entry.optionCount===2)).toBe(true);});
});
