import { mkdtemp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import path from "node:path";
import { describe, expect, it } from "vitest";
import { loadBundles, loadManifest, promoteSnapshot, stageSnapshot, validateSnapshot, verifyManifest } from "../snapshot";

const fixtureDirectory=path.resolve("src/data/snapshots");
describe("complete static snapshot staging",()=>{
 it("stages, checksums, reloads, and reports a complete fixture snapshot without touching active data",async()=>{const bundles=await loadBundles(fixtureDirectory);const baseline=await loadManifest(fixtureDirectory);const stage=await stageSnapshot(bundles,true,fixtureDirectory,baseline);try{expect(stage.report.counts.transfers).toBe(16);expect(stage.manifest.fixture).toBe(true);expect(JSON.parse(await readFile(path.join(stage.directory,"manifest.json"),"utf8")).domains.search.sha256).toBe(stage.manifest.domains.search.sha256);}finally{await rm(stage.directory,{recursive:true,force:true});}});
 it("rejects relationship, search, count, and secret corruption",async()=>{const bundles=await loadBundles(fixtureDirectory);expect(()=>validateSnapshot({...bundles,programs:{...bundles.programs,directory:[{...bundles.programs.directory[0],slug:"missing"}]}},true)).toThrow(/count|unresolved/);expect(()=>validateSnapshot({...bundles,search:{...bundles.search,meta:{...bundles.search.meta,counts:{entries:1}}}},true)).toThrow(/Search index/);expect(()=>validateSnapshot({...bundles,courses:{...bundles.courses,ids:[...bundles.courses.ids,"MISSING"]}},true)).toThrow(/unresolved record/);const secretRows=[...bundles.transfers.rows];secretRows[0]={...secretRows[0],token:"nope"} as never;expect(()=>validateSnapshot({...bundles,transfers:{...bundles.transfers,rows:secretRows}},true)).toThrow(/Potential secret/);});
 it("rejects large drops only against an approved baseline",async()=>{const bundles=await loadBundles(fixtureDirectory);const baseline=await loadManifest(fixtureDirectory);if(!baseline)throw new Error("missing fixture manifest");const approved={...baseline,fixture:false,domains:{...baseline.domains,transfers:{...baseline.domains.transfers,counts:{rows:100}}}};expect(()=>validateSnapshot(bundles,true,approved,.5)).toThrow(/fell below/);expect(validateSnapshot(bundles,true,baseline,.5).baseline).toBe("fixture");});
 it("rejects manifest checksum corruption",async()=>{const bundles=await loadBundles(fixtureDirectory);const manifest=await loadManifest(fixtureDirectory);if(!manifest)throw new Error("missing fixture manifest");expect(()=>verifyManifest(bundles,{...manifest,domains:{...manifest.domains,courses:{...manifest.domains.courses,sha256:"bad"}}})).toThrow(/checksum/);});
 it("promotes by directory swap and restores the old active directory on failed swap",async()=>{const root=await mkdtemp(path.join(tmpdir(),"snapshot-test-"));const active=path.join(root,"active");const stage=path.join(root,"stage");await mkdir(active);await mkdir(stage);await writeFile(path.join(active,"old"),"old");await writeFile(path.join(stage,"new"),"new");const backup=await promoteSnapshot(stage,active);expect(await readFile(path.join(active,"new"),"utf8")).toBe("new");expect(await readFile(path.join(backup,"old"),"utf8")).toBe("old");const badStage=path.join(root,"does-not-exist");await expect(promoteSnapshot(badStage,active)).rejects.toThrow();expect(await readFile(path.join(active,"new"),"utf8")).toBe("new");});
});
