import { describe,expect,it,vi } from "vitest";
import { exportTransfersFromDatabase,transformTransfers } from "../transfers";
import { buildFacetSummaries } from "@/features/transfers/lib/seoQueries";
const row=(courseNumber:string,pid:string,provider:string)=>({subjectPrefix:courseNumber.startsWith("ACC")?"ACC":"CS",courseNumber,title:"Transfer course",pid,eligibilityTimeframe:null,groupFilter2Name:provider,academicLevel:null,coursePID:"target"});
describe("transfers static exporter",()=>{
 it("preserves every option, canonicalizes course lookup codes, and is deterministic",()=>{const rows=[row("cs 210","a","A"),row("CS-210","b","B"),...Array.from({length:13},(_,i)=>row("ACC201",`acc-${i}`,`Provider ${i}`)),{...row("CS210","same-a","Provider"),eligibilityTimeframe:"2025"},{...row("CS210","same-b","Provider"),eligibilityTimeframe:"2026"}];const output=transformTransfers([...rows].reverse(),"2026-01-01");expect(output.meta.counts.rows).toBe(17);expect(output.rows.filter(r=>r.courseNumber==="CS210")).toHaveLength(4);expect(output.rows.filter(r=>r.courseNumber==="ACC201")).toHaveLength(13);expect(buildFacetSummaries(output.rows).courses.find(x=>x.value==="ACC201")?.count).toBe(13);expect(output.lastModified).toBe("2026-01-01T00:00:00.000Z");});
 it("retains null metadata and rejects invalid/empty datasets",()=>{expect(transformTransfers([row("PSY321","p","College")],null).rows[0].academicLevel).toBeNull();expect(()=>transformTransfers([],null)).toThrow(/empty/);expect(()=>transformTransfers([row("not a course","p","x")],null)).toThrow(/Invalid/);});
 it("uses a repeatable read-only transaction and releases after failures",async()=>{const query=vi.fn().mockResolvedValueOnce({rows:[]}).mockResolvedValueOnce({rows:[row("CS210","p","A")]}).mockResolvedValueOnce({rows:[{completed_at:"2026-01-01"}]}).mockResolvedValueOnce({rows:[]});const release=vi.fn();const result=await exportTransfersFromDatabase({connect:vi.fn().mockResolvedValue({query,release})} as never);expect(result.rows).toHaveLength(1);expect(query).toHaveBeenNthCalledWith(1,"BEGIN TRANSACTION ISOLATION LEVEL REPEATABLE READ READ ONLY");expect(query).toHaveBeenLastCalledWith("COMMIT");expect(release).toHaveBeenCalled();const fail=vi.fn().mockResolvedValueOnce({rows:[]}).mockRejectedValueOnce(new Error("read failure")).mockResolvedValueOnce({rows:[]});const releaseFail=vi.fn();await expect(exportTransfersFromDatabase({connect:vi.fn().mockResolvedValue({query:fail,release:releaseFail})} as never)).rejects.toThrow("read failure");expect(fail).toHaveBeenLastCalledWith("ROLLBACK");expect(releaseFail).toHaveBeenCalled();});
});
