import type { Pool } from "pg";
import { CATEGORY_PALETTES } from "@/lib/graphLayout";
import { getCourseNodeId, normalizeCourseCode } from "@/lib/courseCode";
import { normalizeDegreeLevel } from "@/lib/kualiParser";
import { resolvePublicCatalogUrl } from "@/lib/snhuCatalog";
import type { DegreeProgram, GroupCategory, RequirementItem } from "@/types/program";
type ProgramRow = { id: string; slug: string; title: string; credential: string; catalogYear: string; totalCredits: number | null; description: string | null; sourcePid: string | null; syncedAt: Date | string | null };
type GroupRow = { id: string; programId: string; parentId: string | null; title: string; category: GroupCategory; ruleType: string; minimumSelections: number | null; maximumSelections: number | null; minimumCredits: number | null; rawExcerpt: string | null; ruleMetadata: Record<string, unknown> | null };
type CourseRow = { groupId: string; id: string; courseCode: string; title: string; credits: number | null; optional: boolean };
type TextRow = { groupId: string; text: string; unparsed: boolean };
type EdgeRow = { programId: string; source: string; target: string; type: string; label: string | null; title: string | null; credits: number | null };
export type ProgramsExport = { meta: { domain: "programs"; counts: { programs: number } }; directory: Array<Pick<DegreeProgram,"slug"|"title"|"degreeLevel"|"credential"|"catalogYear"|"totalCredits"|"requiredCourseCount"|"description"|"sourceCatalogUrl">>; bySlug: Record<string,DegreeProgram>; sitemap: Array<{slug:string;updatedAt:string|null}>; catalogYears:string[]; lastUpdated:string|null };
const iso=(v: Date|string|null)=>v && !Number.isNaN(new Date(v).getTime())?new Date(v).toISOString():null;
export function transformPrograms(programs: ProgramRow[], groups: GroupRow[], courses: CourseRow[], texts: TextRow[], edges: EdgeRow[]): ProgramsExport {
 const bySlug:Record<string,DegreeProgram>={}; const sorted=[...programs].sort((a,b)=>a.slug.localeCompare(b.slug));
 for(const p of sorted){ if(!p.slug||!p.title||bySlug[p.slug]) continue; const pg=groups.filter(g=>g.programId===p.id); if(!pg.length) throw new Error(`Program ${p.slug} has no requirement groups`); const nodeMap=new Map<string, DegreeProgram["nodes"][number]>(); const itemByGroup=new Map<string,RequirementItem[]>();
  for(const g of pg){ const items:RequirementItem[]=[]; for(const c of courses.filter(c=>c.groupId===g.id)){const code=normalizeCourseCode(c.courseCode); if(!code) throw new Error(`Invalid course in ${p.slug}`); items.push({id:c.id,title:`${c.courseCode}: ${c.title}`,credits:c.credits,type:c.optional?"elective":g.ruleType==="choose_n"?"choice":"single",description:c.optional?"Optional Course":undefined}); if(!nodeMap.has(code)) nodeMap.set(code,{id:getCourseNodeId(code),code,title:c.title,credits:c.credits,groupCode:g.id,groupName:g.title,groupCategory:g.category,prerequisites:[],corequisites:[]}); } for(const t of texts.filter(t=>t.groupId===g.id)){items.push({id:`txt_${items.length}`,title:t.text,credits:null,type:"single",isUnparsed:t.unparsed,textKind:t.unparsed?"unparsed":/policy|eligibility/i.test(t.text)?"policy":"informational"});} itemByGroup.set(g.id,items); }
  const top=pg.filter(g=>!g.parentId).map(g=>{const items=itemByGroup.get(g.id)!; for(const child of pg.filter(x=>x.parentId===g.id)) items.push({id:child.id,title:child.title,credits:child.minimumCredits,type:"group",subItems:itemByGroup.get(child.id),ruleType:child.ruleType,minimumSelections:child.minimumSelections,maximumSelections:child.maximumSelections,minimumCredits:child.minimumCredits,ruleMetadata:child.ruleMetadata??undefined,sourceText:child.rawExcerpt??undefined}); const pal=CATEGORY_PALETTES[g.category]??CATEGORY_PALETTES.core; return {id:g.id,title:g.title,category:g.category,totalCredits:g.minimumCredits,ruleType:g.ruleType,minimumSelections:g.minimumSelections,maximumSelections:g.maximumSelections,minimumCredits:g.minimumCredits,ruleMetadata:g.ruleMetadata??undefined,sourceText:g.rawExcerpt??undefined,items,colorTheme:{bg:pal.bg,border:pal.border,text:"text-slate-900",badgeBg:pal.badgeBg,badgeText:pal.badgeText}}; });
  const graph=[] as DegreeProgram["edges"]; for(const e of edges.filter(e=>e.programId===p.id)){const target=nodeMap.get(normalizeCourseCode(e.target)); if(!target) continue; const source=normalizeCourseCode(e.source), id=getCourseNodeId(source); if(!nodeMap.has(source)) nodeMap.set(source,{id,code:source,title:e.title??"External Requirement",credits:e.credits,groupCode:"external",groupName:"External Prerequisites",groupCategory:"other",isExternal:true,prerequisites:[],corequisites:[]}); if(e.type==="corequisite") target.corequisites=[...(target.corequisites??[]),id]; else target.prerequisites=[...(target.prerequisites??[]),id]; graph.push({id:`e_${id}_${target.id}_${e.type}`,source:id,target:target.id,type:e.type==="corequisite"?"corequisite":"prerequisite",label:e.label??undefined}); }
  bySlug[p.slug]={slug:p.slug,title:p.title,degreeLevel:normalizeDegreeLevel(p.credential),credential:p.credential,catalogYear:p.catalogYear,totalCredits:p.totalCredits,requiredCourseCount:nodeMap.size,electiveCredits:null,estimatedDuration:"Not available",sourcePid:p.sourcePid??undefined,sourceCatalogUrl:resolvePublicCatalogUrl(p.sourcePid),sourceName:"SNHU Academic Catalog",description:p.description??"",groups:top,nodes:[...nodeMap.values()],edges:graph,unparsedRequirements:texts.filter(t=>t.unparsed&&pg.some(g=>g.id===t.groupId)).map(t=>t.text)};
 }
 if(!Object.keys(bySlug).length) throw new Error("Refusing empty programs export"); const directory=Object.values(bySlug).map(p=>({slug:p.slug,title:p.title,degreeLevel:p.degreeLevel,credential:p.credential,catalogYear:p.catalogYear,totalCredits:p.totalCredits,requiredCourseCount:p.requiredCourseCount,description:p.description,sourceCatalogUrl:p.sourceCatalogUrl})); const sitemap=sorted.filter(p=>bySlug[p.slug]).map(p=>({slug:p.slug,updatedAt:iso(p.syncedAt)})); const lastUpdated=sitemap.map(x=>x.updatedAt).filter(Boolean).sort().at(-1)??null; return {meta:{domain:"programs",counts:{programs:directory.length}},directory,bySlug,sitemap,catalogYears:[...new Set(directory.map(d=>d.catalogYear))].sort().reverse(),lastUpdated};
}
export async function exportProgramsFromDatabase(pool:Pick<Pool,"connect">):Promise<ProgramsExport>{const c=await pool.connect();try{await c.query("BEGIN TRANSACTION READ ONLY"); const q=async<T>(sql:string)=> (await c.query(sql) as unknown as {rows:T[]}).rows; const result=transformPrograms(await q<ProgramRow>("SELECT p.id,p.slug,p.title,p.credential,c.year_label AS \"catalogYear\",p.total_credits AS \"totalCredits\",p.description_summary AS description,p.source_pid AS \"sourcePid\",p.synced_at AS \"syncedAt\" FROM programs p JOIN catalogs c ON c.id=p.catalog_id"),await q<GroupRow>("SELECT id,program_id AS \"programId\",parent_group_id AS \"parentId\",title,category,rule_type AS \"ruleType\",minimum_selections AS \"minimumSelections\",maximum_selections AS \"maximumSelections\",minimum_credits AS \"minimumCredits\",raw_excerpt AS \"rawExcerpt\",rule_metadata AS \"ruleMetadata\" FROM program_requirement_groups"),await q<CourseRow>("SELECT id,requirement_group_id AS \"groupId\",course_code AS \"courseCode\",title,credits,is_optional AS optional FROM program_requirement_courses"),await q<TextRow>("SELECT requirement_group_id AS \"groupId\",text,is_unparsed AS unparsed FROM program_text_requirements"),await q<EdgeRow>("SELECT prg.program_id AS \"programId\",e.source_course_code AS source,e.target_course_code AS target,e.relationship_type AS type,e.source_text AS label,dc.title,dc.credits FROM degree_course_edges e JOIN program_requirement_courses prc ON prc.course_code=e.target_course_code JOIN program_requirement_groups prg ON prg.id=prc.requirement_group_id LEFT JOIN degree_courses dc ON dc.course_code=e.source_course_code")); await c.query("COMMIT");return result;}catch(e){await c.query("ROLLBACK").catch(()=>undefined);throw e;}finally{c.release();}}
